### ISSUE TITLE
commas used as proprety seperator

### ISSUE THREAD

**Issue by jiblett1000** [cloudinary/responsive_breakpoints_generator#18]
Hello,

I am using Nuxt3 (which admittedly is still in beta now) and I'm getting an error because of the commas being used as separators in the srcset image urls.

It seems to me that considering commas are used as end of line in the srcset syntax, these would be better off as maybe hyphens or another such character.

**Comment by roeeba** [comment]
Hi @jiblett1000, Can you please share the error message you get and the relevant code that causes it so we can take a deeper look?

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at [https://support.cloudinary.com/hc/en-us/requests/new](http://support.cloudinary.com/) or create a new ticket if you have any additional issues.
