### ISSUE TITLE
which quotas are applied?

### ISSUE THREAD

**Issue by DanielRuf** [cloudinary/responsive_breakpoints_generator#4]
Can we generate as many breakpoints / picture tags as we want or are there any quotas which apply to this tool (your hosted version)?

**Comment by idobarnoam** [comment]
Hi @DanielRuf generating derived images requires the use of transformations. 
Each different transformation is a new derived image.

The transformation quota is different per plan.

You could read more about our quotas in the link below.
https://support.cloudinary.com/hc/en-us/articles/203125631-How-does-Cloudinary-count-my-plan-s-quotas-and-what-does-every-quota-mean-

**Comment by DanielRuf** [comment]
And as already answered on Twitter: you use one of your own accounts for the online tool so we have no quota there that we hit.
